#!/bin/bash

# Create .env from GitHub Secrets (for CI/CD)
set -e

cat > .env << EOF
DOMAIN_NAME=${DOMAIN_NAME}
BACKEND_REPO=${BACKEND_REPO}
FRONTEND_REPO=${FRONTEND_REPO}
BACKEND_PORT=8000
FRONTEND_PORT=3000
MONGODB_URI=${MONGODB_URI}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d
SPORTS_ODDS_API_KEY=${SPORTS_ODDS_API_KEY}
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USER=${EMAIL_USER}
EMAIL_PASS=${EMAIL_PASS}
CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
CCP_APP_ID=${CCP_APP_ID}
CCP_APP_SECRET=${CCP_APP_SECRET}
CCP_MERCHANT_ID=${CCP_MERCHANT_ID}
CCP_API_BASE_URL=https://ccpayment.com/ccpayment/v2
CORS_ORIGINS=https://${DOMAIN_NAME},https://www.${DOMAIN_NAME}
SESSION_SECRET=${SESSION_SECRET}
VITE_API_BASE_URL=https://${DOMAIN_NAME}
VITE_SOCKET_URL=https://${DOMAIN_NAME}
EOF

chmod 600 .env
echo "✅ Environment file created from secrets"